export type Role = 'OWNER' | 'MANAGER' | 'PURCHASER' | 'WAREHOUSE' | 'SALES' | 'FINANCE' | 'AI_AGENT' | 'SYSTEM_EXECUTOR'
export type BusinessAction =
  | 'READ_METRICS' | 'GENERATE_PROPOSAL' | 'APPROVE_PURCHASE' | 'SEND_PURCHASE'
  | 'CHANGE_PRICE' | 'RESERVE_STOCK' | 'RELEASE_STOCK' | 'SCRAP_STOCK'
  | 'SEND_COLLECTION' | 'CHANGE_PAYMENT_TERMS' | 'WRITE_OFF_RECEIVABLE' | 'MANAGE_ROLES'
  | 'EXECUTE_APPROVED_PROPOSAL'

const matrix: Record<Role, BusinessAction[]> = {
  OWNER: ['READ_METRICS','GENERATE_PROPOSAL','APPROVE_PURCHASE','SEND_PURCHASE','CHANGE_PRICE','RESERVE_STOCK','RELEASE_STOCK','SCRAP_STOCK','SEND_COLLECTION','CHANGE_PAYMENT_TERMS','WRITE_OFF_RECEIVABLE','MANAGE_ROLES'],
  MANAGER: ['READ_METRICS','GENERATE_PROPOSAL','APPROVE_PURCHASE','CHANGE_PRICE','RESERVE_STOCK','RELEASE_STOCK','SCRAP_STOCK','SEND_COLLECTION'],
  PURCHASER: ['READ_METRICS','GENERATE_PROPOSAL','SEND_PURCHASE'],
  WAREHOUSE: ['READ_METRICS','RESERVE_STOCK','RELEASE_STOCK'],
  SALES: ['READ_METRICS','GENERATE_PROPOSAL','RESERVE_STOCK','RELEASE_STOCK'],
  FINANCE: ['READ_METRICS','GENERATE_PROPOSAL','SEND_COLLECTION','CHANGE_PAYMENT_TERMS','WRITE_OFF_RECEIVABLE'],
  AI_AGENT: ['READ_METRICS','GENERATE_PROPOSAL'],
  SYSTEM_EXECUTOR: ['EXECUTE_APPROVED_PROPOSAL']
}

export const can = (role: Role, action: BusinessAction) => matrix[role].includes(action)
export const requirePermission = (role: Role, action: BusinessAction) => {
  if (!can(role, action)) throw new Error(`权限不足：${role} 无权执行 ${action}`)
}
export const humanApprovalRequired = (action: BusinessAction) => !['READ_METRICS','GENERATE_PROPOSAL','EXECUTE_APPROVED_PROPOSAL'].includes(action)
